### ISSUE TITLE
Review English text

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petajakarta.org#1]
(As currently deployed to https://static.petajakarta.org/ )

**Comment by anexact** [comment]
PetaJakarta.org has been replaced by PetaBencana.id, an expanded disaster mapping platform currently deployed for Jabodetabek, Surabaya, and Bandung. Please update your bookmarks and click here to view the map and find out more.

BI.

**Comment by fadmastuti** [comment]
@matthewberryman @anexact 

BI -- PetaJakarta.org telah dialihkan menjadi PetaBencana.id, sebuah perluasan platform pemetaan kebencanaan yang saat ini tersedia untuk Jabodetabek, Surabaya, dan Bandung. Cek dan perbarui bookmarks Anda dan klik di sini untuk melihat serta mengeksplor lebih lanjut.

cc @prittandrani please correct me

**Comment by matthewberryman** [comment]
@anexact I went with "(greater Jakarta)" in brackets next to Jabodetabek for clarity for English speakers not local/that familiar with Jakarta.
