### ISSUE TITLE
Review page design

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petajakarta.org#3]

**Comment by matthewberryman** [comment]
As part of this- do we want to redirect automatically?

**Comment by anexact** [comment]
I believe we should just redirect the webpage automatically for the next year, but we should also keep "@petajkt" in the list of handles we listen for via CogniCity.

**Comment by matthewberryman** [comment]
We can redirect automatically after some delay, i.e. page loads with a message, and then petabencana.id loads t seconds later for some t (5 seconds? 10?). @talltom and I will make sure the bot listens to @petajkt as well as the new handle.

**Comment by matthewberryman** [comment]
Aside from redirection https://github.com/urbanriskmap/petajakarta.org/issues/4 - any other page design issues?

**Comment by talltom** [comment]
Nope I think we're good. Note that the multiple handles feature @anexact discusses above is logged here: https://github.com/urbanriskmap/cognicity-reports-powertrack/issues/5

**Comment by matthewberryman** [comment]
Yeah that was already on my to-do list to document as part of launch transition. :)

Regarding page design - before I close this, do you want to include a logo on the page (favicon is already set up)?

**Comment by talltom** [comment]
I think best to leave out logo, else it will start to get complex (sponsors etc).

**Comment by matthewberryman** [comment]
Ok closing this. Open a separate issue if you also want a holding page for rem.petajakarta.org (or do we want to 302 redirect that?)
