### ISSUE TITLE
redirect ?

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petajakarta.org#4]
Do we want to have the page redirect to petabencana.id, and if so, after how long? I've got the [sample page](https://static.petajakarta.org/) set up to redirect to https://petabencana.id (currently showing holding page until we launch), after 10 seconds, which I think is fine.

**Comment by talltom** [comment]
10 seconds works for me.

**Comment by prittandrani** [comment]
10 seconds is fine for me, enough time for people to read the text and not waited too long.

**Comment by matthewberryman** [comment]
@anexact suggests based on discussions with field office around Indonesian (and even my) user behaviour, that users are unlikely to see the redirect as they will swap tabs. Killing this soon.
